-- ================================================================
-- RESTORE ALL LESSON DATA
-- ================================================================
-- This restores all 93 lessons from lessonStructure.js
-- Run this AFTER Migration #1 if lessons were dropped

INSERT INTO lessons (id, section, title, description, difficulty, estimated_minutes, order_index) VALUES
('getting-started', 'getting-started', 'ACT Test Basics & Overview', 'Test format, timing, and scoring overview', 'beginner', 20, 1),
('english-intro', 'english', 'English Section Fundamentals', 'What is on the ACT English Test and what you''ll learn in this course', 'beginner', 15, 2),
('sentence-structure', 'english', 'Building Complete Sentences', 'Independent clauses, dependent clauses, compound sentences, and comma splices', 'beginner', 25, 3),
('commas', 'english', 'Essential Comma Rules', 'Unnecessary information, names rule, listing commas, and adjective lists', 'beginner', 20, 4),
('punctuation', 'english', 'Advanced Punctuation', 'Semicolons, colons, dashes, apostrophes, and quotation marks', 'intermediate', 25, 5),
('verbs', 'english', 'Verb Agreement & Tenses', 'Subject-verb agreement, verb tense, and irregular verbs', 'intermediate', 25, 6),
('pronouns', 'english', 'Pronoun Usage & Agreement', 'Pronoun case, who vs. whom, pronoun agreement, and ambiguous pronouns', 'intermediate', 25, 7),
('modifiers', 'english', 'Modifier Placement', 'Identifying and correcting misplaced modifiers in sentences', 'intermediate', 20, 8),
('parallel-structure', 'english', 'Mastering Parallel Structure', 'Parallel structure in lists and comparisons', 'intermediate', 20, 9),
('misc-topics', 'english', 'Grammar Essentials & Common Errors', 'Commonly confused words, active vs. passive voice, and prepositional idioms', 'intermediate', 25, 10),
('grammar-review', 'english', 'Complete Grammar Review', 'Comprehensive review of all grammar concepts', 'intermediate', 30, 11),
('redundancy', 'english', 'Eliminating Redundancy & Wordiness', 'Identifying and eliminating redundant and wordy expressions', 'intermediate', 20, 12),
('word-choice', 'english', 'Precise Word Choice', 'Selecting the clearest and most precise words in context', 'intermediate', 20, 13),
('transitions', 'english', 'Logical Transitions', 'Choosing logical transitions between sentences and paragraphs', 'intermediate', 20, 14),
('which-choice', 'english', 'Answering Which Choice Questions', 'Answering specific "which choice" questions about content', 'advanced', 25, 15),
('adding-deleting', 'english', 'Adding & Deleting Information', 'Determining when to add or delete information from passages', 'advanced', 25, 16),
('logical-placement', 'english', 'Sentence & Paragraph Placement', 'Placing sentences in the most logical order within paragraphs', 'advanced', 25, 17),
('introduction-to-act-math', 'math', 'Math Section Overview & Strategy', 'Test format, timing, strategies, and essential tips for success', 'beginner', 20, 18),
('backsolving', 'math', 'Working Backwards Strategy', 'Powerful test-taking trick for working backwards from answer choices', 'beginner', 20, 19),
('substitution', 'math', 'Number Substitution Technique', 'Test-taking strategy for plugging in values', 'beginner', 20, 20),
('geometry-angles', 'math', 'Understanding Angles & Lines', 'Intersecting lines, parallel lines, interior angles', 'intermediate', 30, 21),
('2.2', 'math', 'Areas, Volumes & Triangles', 'Area, volume, right triangles, special triangles', 'intermediate', 30, 22),
('2.3', 'math', 'Lines', 'Slope, equations of lines, midpoint, distance formulas', 'intermediate', 30, 23),
('2.4', 'math', 'Arcs and Sectors', 'Circle arc lengths and sector areas', 'intermediate', 25, 24),
('2.5', 'math', 'Circles, Ellipses, and Hyperbolas', 'Conic sections and their equations', 'advanced', 35, 25),
('3.1', 'math', 'Algebra Skills', 'PEMDAS, negative numbers, combining terms', 'beginner', 25, 26),
('3.2', 'math', 'Fractions', 'Operations with fractions and calculator techniques', 'beginner', 25, 27),
('3.3', 'math', 'Exponents and Roots', 'Exponent rules and simplifying radicals', 'intermediate', 30, 28),
('3.4', 'math', 'Logarithms', 'Logarithm basics and change of base rule', 'advanced', 30, 29),
('3.5', 'math', 'Inequalities', 'Solving and graphing inequalities', 'intermediate', 25, 30),
('3.6', 'math', 'Absolute Value', 'Absolute value equations and inequalities', 'intermediate', 25, 31),
('systems-equations', 'math', 'Systems of Equations', 'Elimination, substitution, word problems', 'intermediate', 30, 32),
('quadratics', 'math', 'Quadratics', 'Factoring, quadratic formula, vertex form', 'intermediate', 35, 33),
('functions', 'math', 'Functions', 'Function notation, composition, domain, range', 'intermediate', 30, 34),
('transforming-functions', 'math', 'Shifting and Transforming Functions', 'Function transformations and translations', 'advanced', 35, 35),
('exponential-growth', 'math', 'Exponential Growth and Decay', 'Exponential functions and applications', 'advanced', 30, 36),
('sequences', 'math', 'Sequences', 'Arithmetic and geometric sequences', 'intermediate', 25, 37),
('5.1', 'math', 'Number Theory', 'Types of numbers, GCD, LCM, solution types', 'intermediate', 30, 38),
('5.2', 'math', 'Percentages', 'Percentage calculations, increase/decrease', 'beginner', 25, 39),
('5.3', 'math', 'Ratios and Proportions', 'Ratio problems, proportions, direct/indirect variation', 'intermediate', 30, 40),
('5.4', 'math', 'Unit Conversion', 'Converting units and dimensional analysis', 'intermediate', 20, 41),
('5.5', 'math', 'Scientific Notation', 'Working with very large and small numbers', 'intermediate', 20, 42),
('5.6', 'math', 'Repeating Patterns', 'Patterns in decimals and powers', 'intermediate', 20, 43),
('6.1', 'math', 'Mean, Median, Mode, and Range', 'Basic statistics and weighted averages', 'beginner', 25, 44),
('6.2', 'math', 'Statistics', 'Standard deviation, distributions, data analysis', 'intermediate', 30, 45),
('6.3', 'math', 'Probability', 'Basic probability rules and calculations', 'intermediate', 25, 46),
('6.4', 'math', 'Permutations, Combinations, and Organized Counting', 'Counting principles and arrangements', 'advanced', 35, 47),
('trigonometry', 'math', 'Trigonometry', 'SOH-CAH-TOA, unit circle, trig functions', 'advanced', 40, 48),
('complex-numbers', 'math', 'Complex Numbers', 'Operations with imaginary numbers', 'advanced', 30, 49),
('matrices', 'math', 'Matrices', 'Matrix operations and determinants', 'advanced', 35, 50),
('vectors', 'math', 'Vectors', 'Vector operations and components', 'advanced', 30, 51),
('word-problems', 'math', 'Word Problems', 'Strategies for solving word problems', 'intermediate', 30, 52),
('miscellaneous-topics', 'math', 'Miscellaneous Topics', 'Venn diagrams, logic, patterns, advanced topics', 'advanced', 35, 53),
('reading-intro', 'reading', 'Reading Section Fundamentals', 'What is on the ACT Reading Test and what you''ll learn in this course', 'beginner', 15, 54),
('core-principles', 'reading', '7 Core Principles for ACT Reading', 'Essential principles to understand the difference between correct and incorrect answers', 'beginner', 30, 55),
('finding-correct-answer', 'reading', '3 Strategies for Finding the Correct Answer', 'Put your finger on evidence, read like a lawyer, and eliminate incorrect choices', 'beginner', 25, 56),
('reading-approaches', 'reading', 'How to Approach the Reading Test', 'Finding the right approach for you: 6 different methods to tackle ACT Reading', 'beginner', 30, 57),
('pacing-time-management', 'reading', 'Pacing and 10 Time Management Skills', 'Master timing and learn essential skills to finish all 4 passages', 'intermediate', 25, 58),
('question-types', 'reading', 'How to Spot and Approach the 7 Most Common Types of Questions', 'Broad passage, clear evidence, inference, purpose, main idea, words in context, and comparing passages', 'intermediate', 35, 59),
('breaking-down-questions', 'reading', 'Breaking Down Questions', 'How to identify exactly what the ACT is asking you', 'intermediate', 20, 60),
('answer-choices', 'reading', 'How to Approach the Answer Choices', 'When to read answer choices and how to use them effectively', 'intermediate', 20, 61),
('correct-vs-incorrect', 'reading', 'Correct vs. Incorrect Answer Choices', '5 common types of incorrect answers and how to effectively find the correct answer', 'intermediate', 30, 62),
('words-in-context', 'reading', 'Words in Context Questions', 'How to approach vocabulary questions and determine meaning from context', 'intermediate', 20, 63),
('comparing-passages', 'reading', 'Tips for Comparing Passages Questions', 'Strategies for dual text passages and comparing passage questions', 'advanced', 25, 64),
('working-backwards', 'reading', 'Working Backwards', 'Advanced strategy for going straight to questions without reading the passage first', 'advanced', 30, 65),
('maximizing-score', 'reading', '7 Tips to Maximize Your Reading Score', 'Essential tips including time management, answer patterns, and practice strategies', 'advanced', 25, 66),
('practice-passages', 'reading', 'Practice Passages', '8 full practice passages with detailed explanations to apply your skills', 'intermediate', 60, 67),
('science-introduction', 'science', 'Science Section Basics', 'Test format, timing, and question types overview', 'beginner', 15, 68),
('passage-approach', 'science', 'How to Approach the Passages', 'Charts & graphs strategies, conflicting viewpoints approach, and general tips', 'beginner', 25, 69),
('question-diagnosis', 'science', 'Question Diagnosis', 'Where to look for information in science passages', 'beginner', 20, 70),
('specific-data-point', 'science', 'Specific Data Point Questions', 'Finding exact values from charts, graphs, and tables', 'beginner', 20, 71),
('trends', 'science', 'Trends Questions', 'Identifying patterns and trends in charts, graphs, and tables', 'intermediate', 25, 72),
('approximation', 'science', 'Approximation Questions', 'Estimating values between or outside given data points', 'intermediate', 25, 73),
('multiple-figures', 'science', 'Multiple Figures Questions', 'Using information from multiple charts, graphs, or tables', 'intermediate', 30, 74),
('figures-text', 'science', 'Figures + Text Questions', 'Combining information from figures and experimental descriptions', 'intermediate', 30, 75),
('scatter-plots', 'science', 'Scatter Plots', 'Reading scatter plot graphs and frequency of data collection', 'intermediate', 25, 76),
('inverse-trends-multiple-axes', 'science', 'Inverse Trends and Graphs with Multiple Axes', 'Complex graphs with multiple y-axes and reverse trend analysis', 'advanced', 35, 77),
('two-part-answers', 'science', '2-Part Answers', 'Questions with claims and supporting evidence in answer choices', 'advanced', 30, 78),
('cannot-be-determined', 'science', 'Cannot Be Determined', 'Recognizing when information is not provided in the passage', 'intermediate', 20, 79),
('equations-as-answers', 'science', 'Equations as Answers', 'Identifying which equation correctly models experimental data', 'advanced', 30, 80),
('mixing', 'science', 'Mixing', 'Predicting results when combining solutions or substances', 'intermediate', 25, 81),
('math-on-science', 'science', 'Math on the Science Test', 'Basic calculations and estimation without a calculator', 'intermediate', 25, 82),
('water-knowledge', 'science', 'Water Knowledge', 'Boiling point, freezing point, evaporation, and condensation', 'beginner', 20, 83),
('experimental-setup', 'science', 'Experimental Setup', 'Understanding why certain experimental procedures are used', 'intermediate', 25, 84),
('outside-knowledge', 'science', 'Other Outside Knowledge', 'Genetics, biology, chemistry, and physics concepts for the ACT', 'intermediate', 30, 85),
('conflicting-viewpoints', 'science', 'Conflicting Viewpoints', 'Practice with the unique conflicting viewpoints passage type', 'advanced', 35, 86),
('sentence-structure-practice', 'english', 'Practice: Building Complete Sentences', 'Authentic ACT questions testing sentence structure concepts', 'intermediate', 30, 87),
('commas-practice', 'english', 'Practice: Essential Comma Rules', 'ACT-style questions on comma usage and punctuation', 'intermediate', 30, 88),
('punctuation-practice', 'english', 'Practice: Advanced Punctuation', 'Semicolons, colons, dashes and apostrophes on the ACT', 'intermediate', 30, 89),
('backsolving-practice', 'math', 'Practice: Working Backwards Strategy', 'ACT math problems perfect for backsolving technique', 'intermediate', 30, 90),
('substitution-practice', 'math', 'Practice: Number Substitution Technique', 'Variable problems using substitution method', 'intermediate', 30, 91),
('geometry-angles-practice', 'math', 'Practice: Understanding Angles & Lines', 'Parallel lines, intersecting lines, and polygon angles', 'intermediate', 30, 92),
('geometry-shapes-practice', 'math', 'Practice: Areas, Volumes & Triangles', 'Area, volume, and triangle problems from real ACTs', 'intermediate', 30, 93)
ON CONFLICT (id) DO UPDATE SET
  section = EXCLUDED.section,
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  estimated_minutes = EXCLUDED.estimated_minutes,
  order_index = EXCLUDED.order_index;
